# Generated by Django 3.2.19 on 2023-06-19 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_order_orderhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='orders',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='orders',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='users.order'),
        ),
    ]
