# Generated by Django 3.2.19 on 2023-07-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230619_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='orders',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
