# Generated by Django 3.2.20 on 2023-09-05 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_productreview_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Rating must be at least 1'), django.core.validators.MaxValueValidator(10, 'Rating must be at most 10')]),
        ),
    ]
