# Generated by Django 3.2.20 on 2023-09-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_productreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='title',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(max_length=3000),
        ),
    ]
