# Generated by Django 3.2.20 on 2023-09-06 23:44
import os

from django.conf import settings
from django.db import migrations, models


def apply_default_image(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    default_image_path = os.path.join(settings.MEDIA_ROOT, 'default.svg')

    if os.path.exists(default_image_path):
        Product.objects.filter(image__isnull=True).update(image='product_images/default.svg')
    else:
        print(f"Default image not found at {default_image_path}")


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_product_rating'),
    ]

    operations = [
        migrations.RunPython(apply_default_image),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='product_images'),
        ),
    ]
